### ISSUE TITLE
Pip packages for the Jupyter kernels of GAP/Singular/Pari/...

### ISSUE THREAD

**Issue by nthiery** [sagemath/docker-images#10]
Step 1: get in touch with the authors of those kernels, and build pip packages
Step 2: update the sagemath-jupyter container to include those packages by default

With this, the sagemath-jupyter docker container (and therefore Windows SageMath distribution) would give easy access to all components.

**Comment by embray** [comment]
By and large putting packages on PyPI for installation by pip is simply a matter of:
- Writing a correct `setup.py` (using plain distutils or, ideally, setuptools, depending on what features the package has)
- Use the `setup.py` to register the package on PyPI, and build/upload a source tarball.

**Comment by williamstein** [comment]
I will deploy these all on sagemathcloud too...

On Thursday, February 11, 2016, Erik Bray notifications@github.com wrote:

> By and large putting packages on PyPI for installation by pip is simply a
> matter of:
> - Writing a correct setup.py (using plain distutils or, ideally,
>   setuptools, depending on what features the package has)
> - Use the setup.py to register the package on PyPI, and build/upload a
>   source tarball.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/sagemath/docker-images/issues/10#issuecomment-182795521
> .

## 

Sent from my massive iPhone 6 plus.

**Comment by nthiery** [comment]
Now that those kernels are package for pip and Sage, this has become trivial. See:
  https://github.com/nthiery/test-binder-sage

Should I just move the three relevant lines to our base docker image?

**Comment by nthiery** [comment]
Done by @embray in 0c536f732d9a5999b81e406e612a265280d923cd.
