### ISSUE TITLE
Test failures in Docker container

### ISSUE THREAD

**Issue by embray** [sagemath/docker-images#11]
In my latest run of the tests in the sagemath/sagemath image, this is the only failure I got:

```
$ sage -t /opt/sage-7.0/src/sage/dev/sagedev.py
Running doctests with ID 2016-02-18-15-56-14-04fc4127.
Git branch: develop
Using --optional=gcc,mpir,python2,sage
Doctesting 1 file.
sage -t --warn-long 25.6 /opt/sage-7.0/src/sage/dev/sagedev.py
**********************************************************************
File "/opt/sage-7.0/src/sage/dev/sagedev.py", line 4049, in sage.dev.sagedev.SageDev.upload_ssh_key
Failed example:
    dev.upload_ssh_key(public_key=public_key)
Expected:
    The trac git server requires your SSH public key to be able to identify you.
    Upload ".../id_rsa.pub" to trac? [Yes/no] yes
    File not found: ".../id_rsa.pub"
    Create new ssh key pair? [Yes/no] yes
    Generating ssh key.
    Your key has been uploaded.
Got:
    The trac git server requires your SSH public key to be able to identify you.
    Upload "/home/sage/.sage/temp/a14653a55833/28540/dir_GxnScs/id_rsa.pub" to trac? [Yes/no] yes
    File not found: "/home/sage/.sage/temp/a14653a55833/28540/dir_GxnScs/id_rsa.pub"
    Create new ssh key pair? [Yes/no] yes
    Generating ssh key.
    /opt/sage-7.0/src/bin/sage-native-execute: 8: /opt/sage-7.0/src/bin/sage-native-execute: ssh-keygen: not found
    Key generation failed.
    Please create a key in "/home/sage/.sage/temp/a14653a55833/28540/dir_GxnScs/id_rsa.pub" and retry.
    <BLANKLINE>
    # Use "sage --dev upload-ssh-key" to upload a public key. Or set your key manually at https://trac.sagemath.org/prefs/sshkeys.
**********************************************************************
File "/opt/sage-7.0/src/sage/dev/sagedev.py", line 4057, in sage.dev.sagedev.SageDev.upload_ssh_key
Failed example:
    dev.upload_ssh_key(public_key=public_key)
Exception raised:
    Traceback (most recent call last):
      File "/opt/sage-7.0/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 496, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/opt/sage-7.0/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 858, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.dev.sagedev.SageDev.upload_ssh_key[11]>", line 1, in <module>
        dev.upload_ssh_key(public_key=public_key)
      File "/opt/sage-7.0/local/lib/python2.7/site-packages/sage/dev/sagedev_wrapper.py", line 182, in wrapped
        return f(*args, **kwargs)
      File "/opt/sage-7.0/local/lib/python2.7/site-packages/sage/dev/sagedev.py", line 4079, in upload_ssh_key
        if not self._UI.confirm('Create new ssh key pair?', default=True):
      File "/opt/sage-7.0/local/lib/python2.7/site-packages/sage/dev/user_interface.py", line 116, in confirm
        return self.select(question, ("yes", "no"), default_option) == "yes"
      File "/opt/sage-7.0/local/lib/python2.7/site-packages/sage/dev/cmd_line_interface.py", line 185, in select
        return self._get_input(prompt, options, default)
      File "/opt/sage-7.0/local/lib/python2.7/site-packages/sage/dev/test/user_interface.py", line 80, in _get_input
        return CmdLineInterface._get_input(self, prompt, options, default, input_func)
      File "/opt/sage-7.0/local/lib/python2.7/site-packages/sage/dev/cmd_line_interface.py", line 124, in _get_input
        s = input_func(prompt)
      File "/opt/sage-7.0/local/lib/python2.7/site-packages/sage/dev/test/user_interface.py", line 73, in input_func
        ' question "{0}".'.format(prompt))
    RuntimeError: no answers left in DoctestUserInterface for question "Create new ssh key pair? [Yes/no] ".
**********************************************************************
1 item had failures:
   2 of  13 in sage.dev.sagedev.SageDev.upload_ssh_key
    [880 tests, 2 failures, 54.97 s]
----------------------------------------------------------------------
sage -t --warn-long 25.6 /opt/sage-7.0/src/sage/dev/sagedev.py  # 2 doctests failed
----------------------------------------------------------------------
Total time for all tests: 55.4 seconds
    cpu time: 20.2 seconds
    cumulative wall time: 55.0 seconds
```

**Comment by embray** [comment]
Ah, this test would just require ssh-keygen to be installed in order to work.  ISTM maybe it could be skipped if it were not available?

**Comment by embray** [comment]
The other known test failure is http://trac.sagemath.org/ticket/18721, but as just updated in that ticket this may already be fixed.

**Comment by embray** [comment]
After trying to clean up some build artifacts to decrease the size of the sagemath image, I ran the tests and got a few more failures (in addition to the ones above):

```
sage -t /opt/sage-7.0/src/sage/geometry/lattice_polytope.py  # Timed out
sage -t /opt/sage-7.0/src/sage_setup/find.py  # 1 doctest failed
sage -t /opt/sage-7.0/src/sage_setup/clean.py  # 1 doctest failed
```

Not sure about the lattice_polytope one.  I re-ran it and it passed.  
The other two seem to expect the source tree to be in some particular state, and are maybe artifacts of how I've gone about semi-manually cleaning up the build tree.  

I'll note, interestingly, that not one of the "clean" targets I could find in any of the Makefiles were designed to clean up all build artifacts while leaving the directory in a fully runtime-capable state.  Maybe it's just me but this bugs me, and it seems like an area for improvement...

**Comment by nthiery** [comment]
On Fri, Feb 19, 2016 at 01:31:08AM -0800, Erik Bray wrote:

>    I'll note, interestingly, that not one of the "clean" targets I could
>    find in any of the Makefiles were designed to clean up all build
>    artifacts while leaving the directory in a fully runtime-capable state.
>    Maybe it's just me but this bugs me, and it seems like an area for
>    improvement...

That sounds like a natural and desirable feature indeed.

**Comment by vbraun** [comment]
You _should_ be able to delete everything except `SAGE_LOCAL` and have a working Sage install (without source and artifacts). It certainly doesn't work but that should be how it works

**Comment by vbraun** [comment]
The `ssh-keygen` test should be marked `# optional ssh` or something like that

**Comment by embray** [comment]
@vbraun ISTM for the most part that should work indeed.  I'll play around with that and see if I can improve the situation.

**Comment by nthiery** [comment]
Hi!
I currently get the following test failure which is due to the Sage banner being disabled (the test checks that the version number appears when starting sage):

```
sage -t src/sage/tests/cmdline.py 
init.sage does not exist ... creating
no stored timings available
Running doctests with ID 2016-03-29-20-54-59-60a33f7b.
Git branch: develop
Using --optional=mpir,python2,sage
Doctesting 1 file.
sage -t src/sage/tests/cmdline.py
**********************************************************************
File "src/sage/tests/cmdline.py", line 106, in sage.tests.cmdline.test_executable
Failed example:
    out.find(version()) >= 0
Expected:
    True
Got:
    False
**********************************************************************
File "src/sage/tests/cmdline.py", line 114, in sage.tests.cmdline.test_executable
Failed example:
    out.find(version()) >= 0
Expected:
    True
Got:
    False

**********************************************************************
1 item had failures:
   2 of 235 in sage.tests.cmdline.test_executable
    [234 tests, 2 failures, 43.20 s]
----------------------------------------------------------------------
sage -t src/sage/tests/cmdline.py  # 2 doctests failed
----------------------------------------------------------------------
Total time for all tests: 43.4 seconds
    cpu time: 0.3 seconds
    cumulative wall time: 43.2 seconds
```

**Comment by nthiery** [comment]
@embray: it sounds like we need another workaround for the unicode caracters of the banner that are not digested well under docker on windows.

**Comment by nthiery** [comment]
See also: http://trac.sagemath.org/ticket/20319

**Comment by jdemeyer** [comment]
> I currently get the following test failure which is due to the Sage banner being disabled

Could you just use a non-Unicode banner instead? Then you don't have issues with docker nor with the doctest.

**Comment by nthiery** [comment]
On Wed, Mar 30, 2016 at 05:28:35AM -0700, jdemeyer wrote:

>    Could you just use a non-Unicode banner instead? Then you don't have
>    issues with docker nor with the doctest.

Yes, that's most likely the right thing to do. From what I heard, Erik
went for the quick route of disabling the banner just because there
was already a configuration option for this (the SAGE_BANNER env
variable), so this did not require changing Sage.

Cheers,
                Nicolas

**Comment by fchapoton** [comment]
There is  http://trac.sagemath.org/ticket/20322 to allow for a bare banner if needed

**Comment by embray** [comment]
I think that test should either be skipped depending on the environment, or should explicitly set whatever environment variables it's expecting to find.

**Comment by fchapoton** [comment]
Now that ticket 20322 has solve this failing doctest, the priority is to solve the other failing doctest.
Could you tell us if this other failure also happens on non-windows docker patchbots ?

**Comment by nthiery** [comment]
On Thu, Mar 31, 2016 at 06:16:48AM -0700, Frédéric Chapoton wrote:

>    Now that ticket 20322 has solve this failing doctest,

Thanks!

>    the priority is to solve the other failing doctest.  Could you
>    tell us if this other failure also happens on non-windows docker
>    patchbots ?

Yes indeed. I ran all my tests on a Ubuntu 14.04 box.

Cheers,
                Nicolas

**Comment by embray** [comment]
These particular test failures are no longer relevant since `sage.dev` has been removed.
