### ISSUE TITLE
Pulling `sagemath/sagemath` does not work

### ISSUE THREAD

**Issue by fwilhe** [sagemath/docker-images#2]
There seems to be no `sagemath/sagemath` image on the hub, only `sagemath/sage` ([see](https://hub.docker.com/u/sagemath/))

I would appreciate clarification in the README.

**Comment by sebasguts** [comment]
@nthiery is currently building them. They will be there soon.

**Comment by fwilhe** [comment]
Ok, thanks for the update :)

**Comment by nthiery** [comment]
On Sat, Jan 23, 2016 at 07:19:22AM -0800, Florian Wilhelm wrote:

>    Ok, thanks for the update :)

I added a warning in the README as I should have done from the
beginning.
