### ISSUE TITLE
building the sagemath-develop image

### ISSUE THREAD

**Issue by danielbarter** [sagemath/docker-images#25]
Hi there,

I noticed that the sagemath-develop image on dockerhub is a year old. Is there any plans to keep it up to date?

Alternatively, I would be happy to build the image on my own computer. As far as I can tell, you just need to change `SAGE_BRANCH=master` to `SAGE_BRANCH=develop` in [here](https://github.com/sagemath/docker-images/blob/master/sagemath/Dockerfile), but I am not 100% sure. 

Thanks!

Daniel

**Comment by embray** [comment]
Yes, that is the plan.  The only reason it is not currently being built on a regular basis is that the actual build was broken for a time, in the docker image.  But I think that issue is fixed now.

**Comment by embray** [comment]
IIRC the reason it has `SAGE_BRANCH=master` is that actually points to the latest release of Sage.  If you use the Makefile to build it passes `SAGE_BRANCH=develop` in when building the sagemath-develop image.

**Comment by embray** [comment]
Actually, I'll keep this open as a reminder to try updating the develop image on dockerhub.  I'll go ahead and kick off a build and see if it's working now.

**Comment by embray** [comment]
Okay, I forced an update to the sagemath-develop image even though there are still a couple tests failing, but only due to minor bugs in the tests I think.
