### ISSUE TITLE
Upgrade to Xenial?

### ISSUE THREAD

**Issue by efossas** [sagemath/docker-images#27]
sagemath-base is built on ubuntu:wily which is no longer supported. are there any plans to upgrade it to ubuntu:xenial?

**Comment by embray** [comment]
There are now!

**Comment by embray** [comment]
Done: 0c49d7c  Thanks for raising the suggestion.  I don't think I'll bother rebuilding any of the existing images on DockerHub but subsequent releases will have the new base image.
