### ISSUE TITLE
Push sagemath/sagemath docker image for SageMath 8.1 on dockerhub

### ISSUE THREAD

**Issue by nthiery** [sagemath/docker-images#29]
cc: @embray, @saraedum

**Comment by saraedum** [comment]
I don't have access to sagemath's dockerhub account, so I can't do that. My GitLab/CircleCI build #13  seems to be relatively stable by now. I could bring everything into a "Needs Review" state if you would like to have a look and we could push the new images (automatically) from there.

**Comment by nthiery** [comment]
>    I don't have access to sagemath's dockerhub account, so I can't
>    do that. My GitLab/CircleCI build seems to be relatively stable
>    by now. I could bring everything into a "Needs Review" state if
>    you would like to have a look and we could push the new images
>    (automatically) from there.

I'll have a look later today. In the mean time, I added you to the
owner team of the sagemath organization. I assumed your login was
saraedum as usual.

Cheers,
		Nicolas
--
Nicolas M. Thiéry "Isil" <nthiery@users.sf.net>
http://Nicolas.Thiery.name/

**Comment by saraedum** [comment]
Yes, I'm saraedum there.

**Comment by embray** [comment]
Turns out the 8.1 image got built quite a long time ago (when 8.1 was released) but there was actually a problem with the internet connection (either on our end or dockerhub's; I'm not sure) that prevented the image push from every completing :(

**Comment by embray** [comment]
It's done now, sorry for the atrocious wait.
I need to look into better configuring notification of these failures.

**Comment by nthiery** [comment]
Thanks Erik for investigating!
