### ISSUE TITLE
Install the startup scripts in ~sage/bin

### ISSUE THREAD

**Issue by nthiery** [sagemath/docker-images#6]
The user's `.profile` adds `$HOME/bin` to the PATH if this directory exists. That's where we should put the startup scripts for gap/... This way won't require root access anymore, and we can get rid of the `sage` user being in the sudoers.

**Comment by nthiery** [comment]
Hmm, this raises the question of whether we want to install Sage in /opt on in `$HOME`. In the first case, we still need root access for Sage.

**Comment by nthiery** [comment]
cc @embray

**Comment by embray** [comment]
Could you say more about the "startup scripts for gap/"?  That's something I haven't encountered yet--is there an advantage to them being in the users's home directory?  Is not something that would go into DOT_SAGE or something similar?

**Comment by nthiery** [comment]
This is superseded by sage's local bin dir being in the path in the latest docker image; see:
acbfc7d54d435cf11b6325e93eab2c3dfe9ee48c. Closing issue.
